### ISSUE TITLE
The exe wont send anything to the webhook Im using the V6.0

### ISSUE THREAD

**Issue by JustinWrld** [Itroublve/ItroublveTSC#1]
Hello after creating the exe with no extra options and running it, it wont take or send anything to the webhook any idea on how to fix it, is it an issue on my side I have .net framework

**Comment by Itroublve** [comment]
Hello, could you try to download again and try again. You might be on a older version...

**Comment by Itroublve** [comment]
Actually here is the fixed version, the one on website is broken right now: https://itroublvehacker.gq/fml

**Comment by JustinWrld** [comment]
thanks so much I will try it out and will reply back

**Comment by Itroublve** [comment]
Reopen if it doesn't work. 
Thank you. Source for "V6.1" will be on GitHub after I fix some bugs and when I have time to bother with GitHub's 100 max files upload limit. Thank you for your patience.
