### ISSUE TITLE
Could you Explain some things

### ISSUE THREAD

**Issue by NelsonH75** [Itroublve/ItroublveTSC#11]
1. How to Use (Just In-case I am doing Wrong)
2. Why is it saying I have to convert to ico when already done

**Comment by Itroublve** [comment]
Issue number 1, Select your options and enter webhook create EXE... Make sure you're using the latest version in Releases..

Issue nr 2: Try without a ICO, if the error still persists then it's something wrong, try redownloading... Or try without any options
