### ISSUE TITLE
Discontinued?

### ISSUE THREAD

**Issue by 23wy** [Itroublve/ItroublveTSC#112]
Is the project discontinued or will there be any updates in the future?

**Comment by Itroublve** [comment]
This is discontinued and won't be further updated.

**Comment by 23wy** [comment]
Wait also is the first one under releases the compiled version of the source or has there been any changes?

**Comment by Itroublve** [comment]
> Wait also is the first one under releases the compiled version of the source or has there been any changes made?

Precisely this is the 6th release due to the previous repository being banned. The first version wasn't really anything. And 2nd was just an attempt ig. It was the 3rd release it all started and was written.

So to answer your question, no.

**Comment by 23wy** [comment]
Nvm I'm retarded
