### ISSUE TITLE
Why does this behave like a crypto miner?

### ISSUE THREAD

**Issue by jdghreiongbergm** [Itroublve/ItroublveTSC#116]
I remember on old versions of Windows, it used to open in the background and hid whenever i opened task manager or the dropdown box in the bottom right. Im guessing that encrypted text in this code makes it a crypto miner too.

**Comment by Itroublve** [comment]
Crypto miner? Nice, then how about you show me your high CPU usage, or some other proof perhaps.

**Comment by Rescore0** [comment]
**W itroubvle>>>>** itroublve isnt merciaul retard get a life
