### ISSUE TITLE
injection patched?

### ISSUE THREAD

**Issue by FnDesigns** [Itroublve/ItroublveTSC#120]
for a few days i have been receiving this in my log channel. has the injection method been patched?
![9CFD9AC4-D62B-4515-A374-99259D1BD64B](https://user-images.githubusercontent.com/101824510/158859461-61757c83-457a-4da9-aa3c-4f552c71590f.jpeg)

**Comment by Itroublve** [comment]
Hmm, yea I see. Discord has started encrypting the tokens, I'll have a look at it and be back.

**Comment by Itroublve** [comment]
I mean that was simple to fix.

**Comment by Itroublve** [comment]
Fixed in #121, I'll compile a Release version at a later date when I have time which shall work fine.

**Comment by rikuzx** [comment]
tokens are not working

**Comment by rikuzx** [comment]
nvm got it working again

**Comment by Itroublve** [comment]
> nvm got it working again

Would be amazing if you were to told what exactly you did which fixed it.

**Comment by MrsUnkown** [comment]
Dose this update work with the old launcher itroublve * Launcher in release *

**Comment by FnDesigns** [comment]
> Dose this update work with the old launcher itroublve * Launcher in release *

no not yet..

> Fixed in #121, I'll compile a Release version at a later date when I have time which shall work fine.

**Comment by rikuzx** [comment]
> > nvm got it working again
> 
> Would be amazing if you were to told what exactly you did which fixed it.

didnt do anything at all it only grabs web tokens not app tokens

**Comment by Itroublve** [comment]
I've compiled the code and put it in Release. *the code is still the same*
