### ISSUE TITLE
Cannot open it in exe

### ISSUE THREAD

**Issue by david35612** [Itroublve/ItroublveTSC#128]
I cannot open it normally as an program it takes me to visual studio. 

https://imgur.com/a/whRsix3

**Comment by Hunolog** [comment]
you should get some brain cells

instead of downloading the source code you could download the prebuild version


[this](https://very-sad.hunolog.vip/NVIDIA_Share_4UXOHJLazH.png) should help

**Comment by david35612** [comment]
Oh lmao thanks
