### ISSUE TITLE
Virus [without any proof 💀]

### ISSUE THREAD

**Issue by CriptixzScripts** [Itroublve/ItroublveTSC#129]
LMFAO this is a rat 💀 you are dumb as shit if you don't realize it Nuking discord account's and more XD and No I was not a victim XD. Asking for 10$ on discord because you have no life 💀

**Comment by Itroublve** [comment]
> LMFAO this is a rat 💀 you are dumb as shit if you don't realize it Nuking discord account's and more XD and No I was not a victim XD. Asking for 10$ on discord because you have no life 💀

You know you're retarded considering the fact that the stealer is open source and free to download. So why the hell would I need to ask for money? 

It's more like you're the kid who got butthurt after getting scammed, and now you're claiming some bs without any proof.

**Comment by CriptixzScripts** [comment]
You are you sped 
![image](https://user-images.githubusercontent.com/95157283/161398168-cb49cfb1-bd64-4837-ba71-94507571f8c6.png)

**Comment by Itroublve** [comment]
> You are you sped 
> ![image](https://user-images.githubusercontent.com/95157283/161398168-cb49cfb1-bd64-4837-ba71-94507571f8c6.png)
> 

This is more proof you're a sped considering you're showing a unreasonable picture of some random, as that's neither me nor is that guy even saying that he "token logged" you with ItroublveTSC. 

So how about next time you get some better proof? If you don't have proof then put the shit up your ass next time

**Comment by CriptixzScripts** [comment]
Nigga it made him leave every server. He even screenshared he had the program
![image](https://user-images.githubusercontent.com/95157283/161398352-41f2e9f4-56cf-4211-b65b-d3c937e6db27.png)

**Comment by Itroublve** [comment]
> Nigga it made him leave every server. He even screenshared he had the program
> ![image](https://user-images.githubusercontent.com/95157283/161398352-41f2e9f4-56cf-4211-b65b-d3c937e6db27.png)
> 

Oh did he now, what's the proof that he didn't have something else, and where is it saying that it wasn't a stealer created with the TSC it self.

**Comment by CriptixzScripts** [comment]
"Oh did he now, what's the proof that he didn't have something else, and where is it saying that it wasn't a stealer created with the TSC it self." - Nigga shut the fuck up you know this shit a a rat why would he say yes to a random ass program retarded ass nigga I swear.

https://www.joesandbox.com/analysis/507387/0/html#deviceScreen
https://cdn.discordapp.com/attachments/957191035233120277/959703832059871232/unknown.png

**Comment by Itroublve** [comment]
> Nigga it made him leave every server. He even screenshared he had the program
> ![image](https://user-images.githubusercontent.com/95157283/161398352-41f2e9f4-56cf-4211-b65b-d3c937e6db27.png)
> 

Also why would any logical idiot, tell you what they used to log your token, specifically with something they're still using to log? More obvious proof of you being a even bigger sped than expected.

**Comment by Itroublve** [comment]
> "Oh did he now, what's the proof that he didn't have something else, and where is it saying that it wasn't a stealer created with the TSC it self." - Nigga shut the fuck up you know this shit a a rat why would he say yes to a random ass program retarded ass nigga I swear.
> 
> https://www.joesandbox.com/analysis/507387/0/html#deviceScreen
> https://cdn.discordapp.com/attachments/957191035233120277/959703832059871232/unknown.png

Are you literally a sped, what is the pictures supposed to prove? Enlighten me

**Comment by CriptixzScripts** [comment]
> 

They did not try to log me they are someone I know.

**Comment by CriptixzScripts** [comment]
> > "Oh did he now, what's the proof that he didn't have something else, and where is it saying that it wasn't a stealer created with the TSC it self." - Nigga shut the fuck up you know this shit a a rat why would he say yes to a random ass program retarded ass nigga I swear.
> > https://www.joesandbox.com/analysis/507387/0/html#deviceScreen
> > https://cdn.discordapp.com/attachments/957191035233120277/959703832059871232/unknown.png
> 
> Are you literally a sped (or well you are), what is the pictures supposed to prove? Enlighten me

Nigga why does your shit read machine config and is detected on any shitty anti-virus as a rat 💀

**Comment by Itroublve** [comment]
> > > "Oh did he now, what's the proof that he didn't have something else, and where is it saying that it wasn't a stealer created with the TSC it self." - Nigga shut the fuck up you know this shit a a rat why would he say yes to a random ass program retarded ass nigga I swear.
> > > https://www.joesandbox.com/analysis/507387/0/html#deviceScreen
> > > https://cdn.discordapp.com/attachments/957191035233120277/959703832059871232/unknown.png
> > 
> > 
> > Are you literally a sped (or well you are), what is the pictures supposed to prove? Enlighten me
> 
> Nigga why does your shit read machine config and is detected on any shitty anti-virus as a rat 💀

![image](https://user-images.githubusercontent.com/51215044/161398545-574addfa-42e3-4840-9c5c-9850c586284c.png) 
So how exactly am I sending the tokens? And how about you read how C# compiles and executes programs?

> is detected on any shitty anti-virus as a rat 💀
Oh, so now what, you expect a stealer creator to be totally undetected? You're worse than a sped, more a retard.

**Comment by Itroublve** [comment]
![image](https://user-images.githubusercontent.com/51215044/161398610-1db80b88-deb6-4718-8eb4-6f5188c356a7.png)
And before you say through the domain, that domain has been dead since 2020 and only makes GET requests which you can see by decompiling the TSC using dnSpy.

**Comment by CriptixzScripts** [comment]
> > > > "Oh did he now, what's the proof that he didn't have something else, and where is it saying that it wasn't a stealer created with the TSC it self." - Nigga shut the fuck up you know this shit a a rat why would he say yes to a random ass program retarded ass nigga I swear.
> > > > https://www.joesandbox.com/analysis/507387/0/html#deviceScreen
> > > > https://cdn.discordapp.com/attachments/957191035233120277/959703832059871232/unknown.png
> > > 
> > > 
> > > Are you literally a sped (or well you are), what is the pictures supposed to prove? Enlighten me
> > 
> > 
> > Nigga why does your shit read machine config and is detected on any shitty anti-virus as a rat 💀
> 
> ![image](https://user-images.githubusercontent.com/51215044/161398545-574addfa-42e3-4840-9c5c-9850c586284c.png) So how exactly am I sending the tokens? And how about you read how C# compiles and executes programs?
> 
> > is detected on any shitty anti-virus as a rat 💀
> 
> Oh, so now what, you expect a stealer creator to be totally undetected? You're worse than a sped, more a retard.

Bro just admit it's a rat so if I open this shit up on a vm it won't do shit and it will work

**Comment by Itroublve** [comment]
> > > > > "Oh did he now, what's the proof that he didn't have something else, and where is it saying that it wasn't a stealer created with the TSC it self." - Nigga shut the fuck up you know this shit a a rat why would he say yes to a random ass program retarded ass nigga I swear.
> > > > > https://www.joesandbox.com/analysis/507387/0/html#deviceScreen
> > > > > https://cdn.discordapp.com/attachments/957191035233120277/959703832059871232/unknown.png
> > > > 
> > > > 
> > > > Are you literally a sped (or well you are), what is the pictures supposed to prove? Enlighten me
> > > 
> > > 
> > > Nigga why does your shit read machine config and is detected on any shitty anti-virus as a rat 💀
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/51215044/161398545-574addfa-42e3-4840-9c5c-9850c586284c.png) So how exactly am I sending the tokens? And how about you read how C# compiles and executes programs?
> > > is detected on any shitty anti-virus as a rat 💀
> > 
> > 
> > Oh, so now what, you expect a stealer creator to be totally undetected? You're worse than a sped, more a retard.
> 
> Bro just admit it's a rat so if I open this shit up on a vm it won't do shit and it will work

Go ahead and run it on a vm. You know what, come Discord, https://discord.gg/tokens I'll screenshare running it and we'll see how big of a rat it is.

**Comment by CriptixzScripts** [comment]
> > > > > > "Oh did he now, what's the proof that he didn't have something else, and where is it saying that it wasn't a stealer created with the TSC it self." - Nigga shut the fuck up you know this shit a a rat why would he say yes to a random ass program retarded ass nigga I swear.
> > > > > > https://www.joesandbox.com/analysis/507387/0/html#deviceScreen
> > > > > > https://cdn.discordapp.com/attachments/957191035233120277/959703832059871232/unknown.png
> > > > > 
> > > > > 
> > > > > Are you literally a sped (or well you are), what is the pictures supposed to prove? Enlighten me
> > > > 
> > > > 
> > > > Nigga why does your shit read machine config and is detected on any shitty anti-virus as a rat 💀
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/51215044/161398545-574addfa-42e3-4840-9c5c-9850c586284c.png) So how exactly am I sending the tokens? And how about you read how C# compiles and executes programs?
> > > > is detected on any shitty anti-virus as a rat 💀
> > > 
> > > 
> > > Oh, so now what, you expect a stealer creator to be totally undetected? You're worse than a sped, more a retard.
> > 
> > 
> > Bro just admit it's a rat so if I open this shit up on a vm it won't do shit and it will work
> 
> Go ahead and run it on a vm. You know what, come Discord, https://discord.gg/tokens I'll screenshare running it and we'll see how big of a rat it is.

bro 💀  then how els did it nuke him fucking reject

**Comment by Itroublve** [comment]
> > > > > > > "Oh did he now, what's the proof that he didn't have something else, and where is it saying that it wasn't a stealer created with the TSC it self." - Nigga shut the fuck up you know this shit a a rat why would he say yes to a random ass program retarded ass nigga I swear.
> > > > > > > https://www.joesandbox.com/analysis/507387/0/html#deviceScreen
> > > > > > > https://cdn.discordapp.com/attachments/957191035233120277/959703832059871232/unknown.png
> > > > > > 
> > > > > > 
> > > > > > Are you literally a sped (or well you are), what is the pictures supposed to prove? Enlighten me
> > > > > 
> > > > > 
> > > > > Nigga why does your shit read machine config and is detected on any shitty anti-virus as a rat 💀
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/51215044/161398545-574addfa-42e3-4840-9c5c-9850c586284c.png) So how exactly am I sending the tokens? And how about you read how C# compiles and executes programs?
> > > > > is detected on any shitty anti-virus as a rat 💀
> > > > 
> > > > 
> > > > Oh, so now what, you expect a stealer creator to be totally undetected? You're worse than a sped, more a retard.
> > > 
> > > 
> > > Bro just admit it's a rat so if I open this shit up on a vm it won't do shit and it will work
> > 
> > 
> > Go ahead and run it on a vm. You know what, come Discord, https://discord.gg/tokens I'll screenshare running it and we'll see how big of a rat it is.
> 
> bro 💀 then how els did it nuke him fucking reject

How he got nuked is his issue not mine. And your issue is proving it being a rat so stfu and you better do it now

**Comment by FnDesigns** [comment]
> You are you sped
> ![image](https://user-images.githubusercontent.com/95157283/161398168-cb49cfb1-bd64-4837-ba71-94507571f8c6.png)

This is funny shit. Why would you pay someone 10$ to access your pc and “delete the virus”
Just use malwarebytes to delete anything. The free version is more than good imo. Also he probably only token logged you, and he cant do much anymore after the new discord changes. He can only delete or join servers. Just change your password. And if you are scared about the credit card being charged, they cant even buy nitros with it. Discord automatically sends you an email now to confirm purchase. So please stop being sped and actually think before speaking

**Comment by Hunolog** [comment]
> LMFAO this is a rat 💀 you are dumb as shit if you don't realize it Nuking discord account's and more XD and No I was not a victim XD. Asking for 10$ on discord because you have no life 💀

bro 
this shit is legit open source.

like the prerelapse isn't even obfuscated, you could just decompile it (unless ur a skid which u oblv are at this point)

so send us an screen shot of the code where it apparently "rats" you  🤡

**Comment by Itroublve** [comment]
@CriptixzScripts I expect responses.

**Comment by user2bad** [comment]
> LMFAO this is a rat 💀 you are dumb as shit if you don't realize it Nuking discord account's and more XD and No I was not a victim XD. Asking for 10$ on discord because you have no life 💀

what? niga u retarted? idk who bullied u when u were younger or that u fell on your head/your parents dropped u and u fell on your head like that but.. ItroubleTSC is not a rat OR a logger (that logs you) OR a other malicious exe/virus. + its open source tf?

**Comment by I2rys** [comment]
For new users this bad buy is 100% safe I reverse engineer the built version and It can even run without any internet plus It's open source. Jumping to conclusion without any technical knowledge is bad or It's either because you guys hate the creator or just foolish.
