### ISSUE TITLE
Stealer Not working

### ISSUE THREAD

**Issue by GivingPastes** [Itroublve/ItroublveTSC#135]
I put the webhook in itroublve program and i create the file then run it but nothing happens and i restart discord and it still hasent gotten my token

**Comment by Itroublve** [comment]
I'm aware that there's some issue. I'll have a look on weekend, til then you may use 6.1.1 (if that works, if not lemme know)

**Comment by GivingPastes** [comment]
Ok!

**Comment by Itroublve** [comment]
#137 Fixes this issue.
