### ISSUE TITLE
Hey bro whenever I send it to someone it shows this 

### ISSUE THREAD

**Issue by UNAMED121212** [Itroublve/ItroublveTSC#140]
![image](https://user-images.githubusercontent.com/98811713/162561361-d96d95ad-12f7-48b4-953e-23e35e8fefa5.png)

**Comment by UNAMED121212** [comment]
@Itroublve

**Comment by Itroublve** [comment]
You either zip the file or use something else. Or, you only upload the file once to Discord... As first time it doesn't delete it, rather it's the 2nd time.
