### ISSUE TITLE
i cannot build the stealer it keeps saying this

### ISSUE THREAD

**Issue by kurdx** [Itroublve/ItroublveTSC#141]
i cannot build the stealer it keeps saying this, i even download those
![image](https://user-images.githubusercontent.com/102828847/162625630-d3f7f6c7-b1ef-448f-bf1e-9f8c8d51c886.png)

**Comment by Itroublve** [comment]
Disable your antivirus, extract all files and download again... Shall fix the issue

**Comment by kurdx** [comment]
> Disable your antivirus, extract all files and download again... Shall fix the issue

yeah it worked cuz i extracted the file to my desktop didnt work and in my downloads file it worked

**Comment by kurdx** [comment]
> Disable your antivirus, extract all files and download again... Shall fix the issue

btw can i edit the source code like add a source so it shows the new and old password

**Comment by Itroublve** [comment]
> > Disable your antivirus, extract all files and download again... Shall fix the issue
> 
> btw can i edit the source code like add a source so it shows the new and old password

You can ig.
