### ISSUE TITLE
Stealer that steals your files first?

### ISSUE THREAD

**Issue by MezaKungs** [Itroublve/ItroublveTSC#142]
How many people are falling for this stealer that acctualy stabs and steals their own files its malware

**Comment by Itroublve** [comment]
Here we go, another retard. Go ahead retard, show proof.

**Comment by MezaKungs** [comment]
i dont even need to show the proof cuz its obvious why would someone do something for free?

**Comment by Itroublve** [comment]
If you don't have proof then go away. Your logic is basically like saying why is anything free, make me pay for everything.

**Comment by MezaKungs** [comment]
so your saying u made it as  a charity cuz u have nothing better to do? lol

**Comment by Itroublve** [comment]
> so your saying u made it as  a charity cuz u have nothing better to do? lol 

You have no proof of it being a malware, so I ain't bothering with you
