### ISSUE TITLE
Can't login to tokens

### ISSUE THREAD

**Issue by BumiMandias69** [Itroublve/ItroublveTSC#148]
Hey, not sure if I'm doing it wrong or using something that doesn't work anymore but I can't login to discord tokens that I steal. Is there any suggested thing for logging in with them?

**Comment by Itroublve** [comment]
Assuming they're sent to you from the stealer and aren't 10y old and you're using a working and normal humane method to login, there's no such requirement as 'suggested thing for logging in with them'

**Comment by BumiMandias69** [comment]
ight
