### ISSUE TITLE
Bin Files Missing

### ISSUE THREAD

**Issue by NBTCommunity** [Itroublve/ItroublveTSC#16]
Whenever I try to make a new EXE it says the Bin Files are missing and it wants me to reinstall them, when I try to reinstall it gives me an error. I have turned of antivirus completely and it still hasn't worked. Any help?

**Comment by Itroublve** [comment]
More details needed. Also, don't use the tool to redownload, won't work.

Also, do you have build tools, .net framework, something else forgot.

**Comment by NBTCommunity** [comment]
Got it working.
