### ISSUE TITLE
Failed to create stealer;

### ISSUE THREAD

**Issue by FortnitePlaysz** [Itroublve/ItroublveTSC#167]
Failed to create stealer;
Make sure you have "build tools + .NET FARMEWORK" installed and try again. 

-Been having this issue after and I have uninstalled and reinstalled 

-Anyone have a fix lmk

**Comment by Itroublve** [comment]
Possible solutions:

1) Extract the archive.
2) Make sure you have the things required (BuildTools & .NET Framework for **DEVELOPER** version.
3) Disable your antivirus.
4) Remove the folder and download again.

**Comment by FortnitePlaysz** [comment]
![128584946-0f3c99e6-ab45-44e3-9fba-49cc9dfa2145](https://user-images.githubusercontent.com/44149987/182057973-aac9917a-19a6-4c0c-b848-d4f82494b080.png)

-Make sure all of your anti virus is off and reinstall all of the files (FIXED)
