### ISSUE TITLE
i have tested it on and rdp but now i got it on my pc but when i download it my pc was threat ransomeware every virus [rotection just scared me so i want to know if the builder also works as the file it builds?

### ISSUE THREAD

**Issue by xXNarendra7Xx** [Itroublve/ItroublveTSC#20]

**Comment by Itroublve** [comment]
Well, I can't make you believe something, as you mentioned you have a RDP, you can create stealer and test or do whatever you want on there...

But I assure you it's not any kind of stealer or something, the rest is up to you.
