### ISSUE TITLE
Unable to Download

### ISSUE THREAD

**Issue by RudraRajput1** [Itroublve/ItroublveTSC#22]
hey there!whenever i try to download Itroublve TSC from releases my chrome says 'Failed-Virus detected' is it really safe? And pls tell ur Discord Username and Tag so i can contact you.

**Comment by OG4EVER** [comment]
It will almost always say that but this from the github is trustable

**Comment by RudraRajput1** [comment]
> It will almost always say that but this from the github is trustable

how to resolve it then?

**Comment by OG4EVER** [comment]
You have to disable your antivirus, just be careful with what you install
you will have to have your antivirus disabled or it will delete the files.
