### ISSUE TITLE
Guide for noobs

### ISSUE THREAD

**Issue by OG4EVER** [Itroublve/ItroublveTSC#23]
Hey i am able to build it into a exe file but when i try to create the token  after inserting the webhook it says that the bin files are not in the folder.

**Comment by Itroublve** [comment]
Well, the files has most likely been modified... Try redownloading the stealer, also make sure it's the latest verison (v6)... And that you've got BuildTools & .NET Framework for devs version.

**Comment by Ssundiezk444** [comment]
is ItroublveTSC 6.1 expired/patched as when i try to use it it does not seem to be sending me the information anymore, i have been using the exe file for some time and now when ppl download it it does not send me any information,

**Comment by Itroublve** [comment]
> is ItroublveTSC 6.1 expired/patched as when i try to use it it does not seem to be sending me the information anymore, i have been using the exe file for some time and now when ppl download it it does not send me any information,

Most likely someone got your webhook and deleted it or something else.
