### ISSUE TITLE
How can I use the File Stealer?

### ISSUE THREAD

**Issue by KenWhat** [Itroublve/ItroublveTSC#24]
Okay..
I don't know how to use it... 
Can someone explain?

**Comment by RudraRajput1** [comment]
Just download the exe file and use it...

**Comment by Itroublve** [comment]
You'll have to enter path to the file... It's all explained in the poor textbox, but keep in mind that the "File Location", must be in **Code Lang.**, ex. ```@"path/to/whatever"``` or ``Environment.Username + "/public/../../"``
