### ISSUE TITLE
Downloading issue

### ISSUE THREAD

**Issue by Elkonu** [Itroublve/ItroublveTSC#25]
So, i downloaded the file. But i cant find the exe. Can someone help please?

**Comment by Itroublve** [comment]
. _.

**Comment by Itroublve** [comment]
Well. You downloaded the source, instead download the release compiled binary.

**Comment by DecryptableByte** [comment]
make a folder on your desktop or somewhere else then go and make an anti virus exclusion on that folder

try and save the itroublveTSC and every other file to that folder and you'll have no problem :)

**Comment by Nukedroid123** [comment]
> make a folder on your desktop or somewhere else then go and make an anti virus exclusion on that folder
> 
> try and save the itroublveTSC and every other file to that folder and you'll have no problem :)

tutorial on youtube please....................................................................................................................

**Comment by Me15234** [comment]
An advice, never download token grabber in YouTube cauz the guy who made the video token grab you. If you want the exe go to release, and itroublveTSC 6.1, there is a .rar . Download and extract in a file . There is a bin folder and TroublveTSC.exe

**Comment by Abz1344** [comment]
I'm having trouble aswell, can anyone help?
