### ISSUE TITLE
Help plz

### ISSUE THREAD

**Issue by Me15234** [Itroublve/ItroublveTSC#37]
Hi , I got token grabbed with this tool at a youtube mega link. I know that i'm got logged cauz after i clicked at ItroublveTSC.exe the exe disappear after a fue second and my antivirus was disable. And I want to ask you how can I remove this of my computer plz.

**Comment by Me15234** [comment]
No that’s alright cauz I make a exe an test it to my self and for look I modify my password and restart my pc and after I view my new token in my channel who have webhook. After this I try completely remove discord and reinstall it, I modify my password and reboot my pc ,after I do this I don’t view my new token anymore

**Comment by Me15234** [comment]
And yes I already reset os

**Comment by Levi123245** [comment]
> And yes I already reset os

hey bro, this guy who grabbed u is called nowzee?

**Comment by Me15234** [comment]
No ,he is French

**Comment by Me15234** [comment]
He put a mega link in description who contain .rar who contain bin folder and false Itroublve.exe

**Comment by kantlov112** [comment]
hello i cannot run my token thing to token grab my target
