### ISSUE TITLE
can you give server invite cause the one you sent last doesn't work

### ISSUE THREAD

**Issue by uhuhuhuhuhuhuhuh** [Itroublve/ItroublveTSC#4]

**Comment by uhuhuhuhuhuhuhuh** [comment]
; )

**Comment by JustinWrld** [comment]
yeah i need it @Itroublve i want to ask you something

**Comment by uhuhuhuhuhuhuhuh** [comment]
Lego Person#1225 my discord

**Comment by Itroublve** [comment]
Oh hello, I tried finding this ticket but couldn't so gave up... Thank you for the mention tho. 


It was a good thing you guys didn't join old server because that one was too good :/

Server: https://discord.gg/xTByzPxCwY
Username: Itroublve#0805

**Comment by Itroublve** [comment]
@JustinWrld @uhuhuhuhuhuhuhuh

**Comment by JustinWrld** [comment]
@Itroublve your missing a number lmao its #4numbers

**Comment by Itroublve** [comment]
https://discord.gg/8qz8ygeHGW
