### ISSUE TITLE
how to do i fix the bin error ans this how to fix specifed key is not a vaild size fir this algorithm

### ISSUE THREAD

**Issue by Dacloutty** [Itroublve/ItroublveTSC#41]
![Screenshot 2021-08-30 073451](https://user-images.githubusercontent.com/89791429/131356235-eb55d0c8-aa4f-4e83-894c-a13a045e02d0.png)

**Comment by Itroublve** [comment]
Where did you find it exactly? The download, send it here if you don't mind so I can test it...

**Comment by ENDERM4NQ** [comment]
> 
> 
> Where did you find it exactly? The download, send it here if you don't mind so I can test it...

Hey i have been having the same issue, I got the download from your github (I build it from src, and yes im sure i didnt break anything) After building the project i added bin folder to location of an exe and the webhook input dosent seem to work correctly I hope you can help me.

**Comment by Itroublve** [comment]
Temporarily fixed the issue with another keyset, will change it one day...
