### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Me15234** [Itroublve/ItroublveTSC#42]
Today, I want to create a token grabber with your builder for test it to myself . when I create the token grabber I didn't send it anywhere but in my webhook i received info of a computer who is in windows 7 no discord  . i show you the screenshot. But idk woh he click on this whereas i don't send it everywhere .
![screenshot](https://user-images.githubusercontent.com/89612698/131496965-d64f623d-5c84-405c-995b-85b4e6cb5d9a.png)

**Comment by Me15234** [comment]
and now ther is other info like this but idk if this is virtual box

**Comment by Itroublve** [comment]
It's VirusTotal.
