### ISSUE TITLE
ima  retard. what this shit meanin. 

### ISSUE THREAD

**Issue by ballsucker21** [Itroublve/ItroublveTSC#52]
![image](https://user-images.githubusercontent.com/90458361/132856412-41d75be0-04c3-4223-b537-4b078a382d6f.png)
im like autistic so what this shit mean 
also this 
![image](https://user-images.githubusercontent.com/90458361/132856490-922f994f-6f6c-4097-9e04-d1a5df50049d.png)
its when i try to make the stealer, both of those pop up lol

**Comment by Itroublve** [comment]
It simply means CMD doesn't exist smh.
