### ISSUE TITLE
how do i open the app

### ISSUE THREAD

**Issue by Turker2018discord** [Itroublve/ItroublveTSC#54]
Hello , i downloaded the zip file and i don't know which one is the correct one to open the app.

i can't find the .exe thing.
![image](https://user-images.githubusercontent.com/84833624/132949073-347faa91-447b-4ba6-9f7e-cd0d088d420e.png)
i also browsed the itrouble folder but couldnt find.
help please.

**Comment by Itroublve** [comment]
....

**Comment by Turker2018discord** [comment]
> ....

?

**Comment by AstroOnYT** [comment]
fucking idiot

**Comment by Turker2018discord** [comment]
> fucking idiot

Fucking kid.
There is literally no exe file in there, fuck you.

**Comment by Nukedroid123** [comment]
> > fucking idiot
> 
> Fucking kid.
> There is literally no exe file in there, fuck you.

His the kid when u cant figure out how to download the rar xD

**Comment by Turker2018discord** [comment]
> > > fucking idiot
> > 
> > 
> > Fucking kid.
> > There is literally no exe file in there, fuck you.
> 
> His the kid when u cant figure out how to download the rar xD

Kid i literally downloaded the rar.
İn the folder itself i cant find files to open the grabber, get a life.

**Comment by natosffs** [comment]
fr bruh can u just tell us pls bruh @Itroublve

**Comment by natosffs** [comment]
@Turker2018discord did u figure it out i need help too

**Comment by Turker2018discord** [comment]
> @Turker2018discord did u figure it out i need help too

no

**Comment by natosffs** [comment]
> > @Turker2018discord did u figure it out i need help too
> 
> no

fuck bruhb

**Comment by Hunolog** [comment]
im losing brain cells

**Comment by Itroublve** [comment]
#57

**Comment by Nukedroid123** [comment]
> > > > fucking idiot
> > > 
> > > 
> > > Fucking kid.
> > > There is literally no exe file in there, fuck you.
> > 
> > 
> > His the kid when u cant figure out how to download the rar xD
> 
> Kid i literally downloaded the rar. İn the folder itself i cant find files to open the grabber, get a life.
Bro you downloaded the zip you said it yourself retard

**Comment by Nukedroid123** [comment]
> im losing brain cells by reading this

Same

**Comment by Itroublve** [comment]
Been a while since this issue was closed smh

**Comment by Nukedroid123** [comment]
> Been a while since this issue was closed smh

Ik. I just dont care.
