### ISSUE TITLE
How do I fully uninstall

### ISSUE THREAD

**Issue by a1ot** [Itroublve/ItroublveTSC#55]
I installed itrouble and also made a stub and I ran it to test it out I believe I had the option to run on startup and when I try to delete the folder it has a hidden item in the folder that s being ran which I can't deleted and I just caught itrouble logo in my hidden items.

**Comment by a1ot** [comment]
nvm I figured it out it killed my pc for a while doe

**Comment by kevinyang07** [comment]
how did you do it

**Comment by Itroublve** [comment]
Run: shell:startup & remove all the WindowsUpdatexxx*.exe files. Also, probably a good habit to clean install Discord.

* = xxx, representing integers.
