### ISSUE TITLE
Is this a good option, if my primary use is snagging the saved browser passwords?

### ISSUE THREAD

**Issue by whistledog** [Itroublve/ItroublveTSC#56]
I know the feature is included I guess I just don't understand why you'd want someone else's discord acct. like what can you do on theirs that you can't do on your own? Haha not being a dick just generally wondering.

**Comment by Itroublve** [comment]
Well, I don't really know xD. When I added the password stealer option it was a token stealer from the start... So just Yea idk xD

**Comment by Itroublve** [comment]
And extra options is always a + xD

**Comment by natosffs** [comment]
> I know the feature is included I guess I just don't understand why you'd want someone else's discord acct. like what can you do on theirs that you can't do on your own? Haha not being a dick just generally wondering.

how do i open the menu

**Comment by Itroublve** [comment]
#57
