### ISSUE TITLE
tell me how to open this shit 

### ISSUE THREAD

**Issue by natosffs** [Itroublve/ItroublveTSC#57]
im new to this shit like wtf do i d
![Skjermbilde (90)](https://user-images.githubusercontent.com/90924389/133822181-15b5ab3f-985c-4222-8379-d4207d50b163.png)

**Comment by natosffs** [comment]
@Itroublve

**Comment by natosffs** [comment]
@Itroublve u there bruh i need help

**Comment by Itroublve** [comment]
How long you been using GitHub for? 12h?

**Comment by Itroublve** [comment]
Cuz you obviously don't know where to find the 'Releases' tab

**Comment by pizzalover32** [comment]
> im new to this shit like wtf do i d
> ![Skjermbilde (90)](https://user-images.githubusercontent.com/90924389/133822181-15b5ab3f-985c-4222-8379-d4207d50b163.png)

bruh just download this one https://github.com/Itroublve/ItroublveTSC/releases/download/6.1/ItroublveTSC.v6.Fix.7.2.rar

**Comment by pizzalover32** [comment]
> > im new to this shit like wtf do i d
> > ![Skjermbilde (90)](https://user-images.githubusercontent.com/90924389/133822181-15b5ab3f-985c-4222-8379-d4207d50b163.png)
> 
> bruh just download this one https://github.com/Itroublve/ItroublveTSC/releases/download/6.1/ItroublveTSC.v6.Fix.7.2.rar

its legit release use winrar or 7zip to extract
