### ISSUE TITLE
random tokens?

### ISSUE THREAD

**Issue by wafflxs** [Itroublve/ItroublveTSC#60]
Hi there I've been getting random screenshots and desktop info of random users on my webhook to whom I didn't send my logger to ever since i input my webhook in the builder. Could anyone explain that?

![image](https://user-images.githubusercontent.com/81107743/134387752-ecef21f9-4440-4e75-8aeb-d44d85823c29.png)

**Comment by Itroublve** [comment]
Hey there, that only occurs if you've ran it on VirusTotal (or other anti-malware debug thing)
