### ISSUE TITLE
huh

### ISSUE THREAD

**Issue by ballsucker21** [Itroublve/ItroublveTSC#61]
![image](https://user-images.githubusercontent.com/90458361/134736499-9faac73c-ed0c-4783-a288-d0fde70d0d2e.png)
my discord always tends to slow down suddenly when i accidentally open this shit again, explain???!

**Comment by Itroublve** [comment]
That's not my problem. Fix it or don't use it, didn't force you or ask you to use it? 
It's up to you, what you wanna do.
