### ISSUE TITLE
Is this x64 or x86(32 bit) ?

### ISSUE THREAD

**Issue by AMRIT-cmd** [Itroublve/ItroublveTSC#7]
This came up while opening the ItroubleveTSC.exe
![image](https://user-images.githubusercontent.com/71064814/117803647-814a1b00-b274-11eb-9cf6-63a18342b397.png)
This came up trying to open test.exe
<img width="762" alt="Screenshot 2021-05-11 at 4 21 48 PM" src="https://user-images.githubusercontent.com/71064814/117804254-311f8880-b275-11eb-917e-d7de25386358.png">

**Comment by Itroublve** [comment]
The first error is due to the version check website being reported for fraud... The second error is due to the antivm. It works fine on normal machines on both 32/64bit compatible machines.
