### ISSUE TITLE
how i open the tool from source code

### ISSUE THREAD

**Issue by toolsfordiscord** [Itroublve/ItroublveTSC#79]

**Comment by toolsfordiscord** [comment]
how i open the tool from source code

**Comment by Itroublve** [comment]
You either use Visual Studio 2019/2022 or you use any kind of IDE and compile it using `dotnet`

**Comment by toolsfordiscord** [comment]
I HAVE VSC BUT HOW I OPEN IT FROM SOURCE COD E?

**Comment by toolsfordiscord** [comment]
WHAT I WRITE ?

**Comment by Itroublve** [comment]
Figure it out, I'm no teacher.
