### ISSUE TITLE
i cant find ItroublveTSC exe

### ISSUE THREAD

**Issue by DeratonTrix** [Itroublve/ItroublveTSC#85]
i cant find ItroublveTSC exe like where i open it please help me
![image_2021-11-21_212622](https://user-images.githubusercontent.com/94805186/142777746-d075a3f6-fae6-428d-89c1-837dca1db850.png)

**Comment by DeratonTrix** [comment]
@Itroublve

**Comment by Itroublve** [comment]
Releases... Not the source.

**Comment by Itroublve** [comment]
https://github.com/Itroublve/ItroublveTSC/releases/tag/6.1
