### ISSUE TITLE
Files not found

### ISSUE THREAD

**Issue by swinga111** [Itroublve/ItroublveTSC#92]
When i press on ''Create Stealer'' it says that it has to download files from GitHub (https://gyazo.com/2b628b97442f1dd7771fe6bdddc43b87), i press on Yes and after that im getting this error: https://gyazo.com/dc6a8f27d44261754d2b87ff3490b8f
![12](https://user-images.githubusercontent.com/87228519/146266788-0295b026-0573-4ca0-94b9-0795e483fc44.png)
![1](https://user-images.githubusercontent.com/87228519/146266795-fdc6d993-dc0e-432d-9ee8-bd96b6771795.png)
b

**Comment by swinga111** [comment]
@Itroublve

**Comment by Itroublve** [comment]
The thing is, that doesn't work anymore due to reasons. So try removing it all and downloading again from GitHub, with your antivirus off of course.
