### ISSUE TITLE
C:\temp\finalres.bat Where is it

### ISSUE THREAD

**Issue by Jerrynh770** [Itroublve/ItroublveTSC#94]

**Comment by Itroublve** [comment]
If you mean V5, then it's called TokenStealer.bin, in the "DLL & BINS" folder.

**Comment by Jerrynh770** [comment]
do you have a discord for ItroublveTSC??

**Comment by Jerrynh770** [comment]
cannot find a file finalresbatch error

**Comment by Itroublve** [comment]
> cannot find a file finalresbatch error
> 

Wdym, what are you doing smh
