### ISSUE TITLE
failed to create stealer

### ISSUE THREAD

**Issue by Rescore0** [Itroublve/ItroublveTSC#98]
it says failed to create it asked for me to install a few thing which i did and still it didnt fix naything

**Comment by Itroublve** [comment]
Steps 
- Disable antivirus & Extract again.
- Extract it
- Confirm you've got Build Tools & .NET Framework (4.7+)
- Try without a custom icon (Might be that the ico was rendered incorrectly)

**Comment by Rescore0** [comment]
ok thanks

**Comment by Rescore0** [comment]
It worked tysm
